### ISSUE TITLE
use nvmain with timingcpu(TimingSimpleCPU or others) in gem5 fs mode and kernel is 4.x ,it  aborted.

### ISSUE THREAD

**Issue by WonderWei** [SEAL-UCSB/NVmain#7]

**Comment by WonderWei** [comment]
after i delete “assert” in timing.cc, it can start but takes a long time no to work(more than 3 hours)

**Comment by WonderWei** [comment]
My command is like this, "sudo build/X86/gem5.opt configs/example/fs.py   --kernel=...  --cpu-type=TimingSimpleCPU --mem-type=NVMainMemory --nvmain-config=../nvmain/Config/Hybrid_example.config"

**Comment by Adrien3795** [comment]
> My command is like this, "sudo build/X86/gem5.opt configs/example/fs.py --kernel=... --cpu-type=TimingSimpleCPU --mem-type=NVMainMemory --nvmain-config=../nvmain/Config/Hybrid_example.config"

I am facing a similar issue, when using the 3D_DRAMCache_example and 3D_DRAM_exampls config files. segmentation fault !
have you find solution ? 
![Capture](https://user-images.githubusercontent.com/82516821/118537302-16ee1a80-b74d-11eb-935c-9eae64d75b9c.PNG)
